run:
  build-tags:
    - tasks
linters-settings:
  goimports:
    local-prefixes: github.com/brevdev/dev-plane
  revive:
    min-confidence: 0.8
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      # - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
      - name: unreachable-code
      - name: redefines-builtin-id
  gocyclo:
    min-complexity: 15
  misspell:
    locale: US
  nolintlint:
    allow-leading-space: false # require machine-readable nolint directives (with no leading space)
    allow-unused: false # report any unused nolint directives
    require-explanation: true # require an explanation for nolint directives
    require-specific: false # don't require nolint directives to be specific about which linter is being skipped
  funlen:
    lines: 100
  errcheck:
    exclude-functions:
      - (*encoding/json.Encoder).Encode
  wrapcheck:
    ignoreSigs:
      - .WrapAndTrace
      - .Errorf
      - .Wrap
      - .New
      - .ValidateStruct
      - .Permanent
      - .Decode
  stylecheck:
    checks: ["all", "-ST1020", "-ST1000", "-ST1021"]

linters:
  # please, do not use `enable-all`: it's deprecated and will be removed soon.
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: true
  enable:
    - errcheck
    # - gosimple # don't like
    - govet
    - ineffassign
    # - staticcheck # broken in collections pkg?
    - typecheck
    - bodyclose
    - unused
    # - depguard
    - dupl
    - copyloopvar
    - forcetypeassert
    - funlen
    # - gci # don't like
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    # - godot # don't like
    - gofumpt
    - revive
    # - gomnd # don't like
    - goprintffuncname
    - gosec
    # - ifshort # don't like
    - misspell
    - noctx
    - nolintlint
    - rowserrcheck # broken with generics
    - sqlclosecheck # broken with generics
    - stylecheck
    # - thelper
    - tparallel
    - unconvert
    - unparam
    - whitespace
    # - errorlint
    # - goerr113
    # - wrapcheck
issues:
  # enable issues excluded by default
  exclude-use-default: false
  exclude:
    - composites
  exclude-dirs:
    - internal/lambdalabs/gen