version: "2"
run:
  build-tags:
    - tasks
linters:
  default: none
  enable:
    - bodyclose
    - copyloopvar
    - dupl
    - errcheck
    - forcetypeassert
    - funlen
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - misspell
    - noctx
    - nolintlint
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - tparallel
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    errcheck:
      exclude-functions:
        - (*encoding/json.Encoder).Encode
    funlen:
      lines: 100
    gocyclo:
      min-complexity: 15
    misspell:
      locale: US
    nolintlint:
      require-explanation: true
      require-specific: false
      allow-unused: false
    revive:
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: context-as-argument
        - name: context-keys-type
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: if-return
        - name: increment-decrement
        - name: var-naming
        - name: var-declaration
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: unexported-return
        - name: errorf
        - name: empty-block
        - name: superfluous-else
        - name: unused-parameter
        - name: unreachable-code
        - name: redefines-builtin-id
    staticcheck:
      checks:
        - all
        - -ST1000
        - -ST1020
        - -ST1021
    wrapcheck:
      ignore-sigs:
        - .WrapAndTrace
        - .Errorf
        - .Wrap
        - .New
        - .ValidateStruct
        - .Permanent
        - .Decode
  exclusions:
    generated: lax
    rules:
      - path: (.+)\.go$
        text: composites
    paths:
      - internal/lambdalabs/gen
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofumpt
  settings:
    goimports:
      local-prefixes:
        - github.com/brevdev/dev-plane
  exclusions:
    generated: lax
    paths:
      - internal/lambdalabs/gen
      - third_party$
      - builtin$
      - examples$
