name: LambdaLabs Validation Tests

on:
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:
    # Allow manual triggering
  pull_request:
    paths:
      - 'internal/lambdalabs/**'
      - 'pkg/v1/**'
    branches: [ main ]

jobs:
  lambdalabs-validation:
    name: LambdaLabs Provider Validation
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'run-validation'))
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.0'
        
    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
          
    - name: Install dependencies
      run: make deps
      
    - name: Run LambdaLabs validation tests
      env:
        LAMBDALABS_API_KEY: ${{ secrets.LAMBDALABS_API_KEY }}
      run: |
        cd internal/lambdalabs
        go test -v -short=false -timeout=20m ./...
        
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: lambdalabs-validation-results
        path: |
          internal/lambdalabs/coverage.out
